name: Terminator
version: '${project.version}'
main: dev.mitra88.terminator.Terminator
api-version: '1.21'
load: STARTUP
authors: [Mitra-88]
description: Terminator is a Spigot plugin inspired by the Terminator from Hypixel Skyblock.
website: https://github.com/Mitra-88/Terminator
commands:
  giveterminator:
    usage: /giveterminator
    description: Gives the Terminator item to the player.
permissions:
  terminator.give:
    default: true
    description: Allows players to use the /giveterminator command.